### ISSUE TITLE
Libretro 'Controller Info / Input Info' Updating

### ISSUE THREAD

**Issue by XenuIsWatching** [Skurdt/SK.Libretro#14]
Digging through the input handler. I see where the callbacks happen from a core (such as pcsx-rearmed) and descriptors are sent over which will descript the possible controller info (such as standard, dualshock, negcon, guncon, mouse, (and an empty string for some reason? "")). But these then get stored in to private variables such as `_controllerDescriptions ` which never get used again, nor there is any way to access it. The same goes for the input mapping with `_inputDescriptors` and `_buttonDescriptions` which will describe all the input buttons.

I see there is a variable loaded with `ControllersMap     = wrapper.InputHandler.DeviceMap;` within the bridge, but this just empty. Never set up.

What I'm trying to figure out here is how to remap buttons and select the device type (dualshock, standard, etc...) for a specific port within the API, but it isn't clear how that is to be done here. Is there something I'm missing with this?

**Comment by XenuIsWatching** [comment]
Still trying to actively investigate myself....but just making a note here of a bug I found with recording the Controller Info with this line here: https://github.com/Skurdt/SK.Libretro/blob/cf14f8392a40119542a9e0d66a89d096ec4aa4db/Scripts/Input/InputHandler.cs#L302

As `controllerDescription` is a stack variable, this added by reference in to the `_controllerDescriptions` List.... but as soon as the next loop comes, that stack variable is updated with a new value and therefore that first value that was just added to the List is then updated and the previous data is lost. 

A fix (or workaound) I did here was to just change it to this
```cs
_controllerDescriptions.Add(new retro_controller_description
{
    id = controllerDescription.id,
    desc = controllerDescription.desc,
});
```

**Comment by Skurdt** [comment]
To tell a core what id to use (at least for pcsx), it's on the bridge class using SetControllerPortDevice(port, device).

I had a working UI with names like Lightgun/DualShock/etc... but it looks like the refactoring wasn't finished...
You should be able to access the id to name mapping by making the _controllerDescriptions/_controllersInfo variables public and public properties on the bridge to access them. They should not be empty if the core calls the SetControllerInfo callback.

I'm not sure what you mean by stack variable being updated.
This is a local variable but it's both a class and is created using Marshal.PtrToStructure<T> so it's obviously not on the stack. And even then, when the loop comes around it created a new variable altogether.
I never had any issues creating a new instance of a class and add it to a list, but maybe there's something else going on?

**Comment by XenuIsWatching** [comment]
> To tell a core what id to use (at least for pcsx), it's on the bridge class using SetControllerPortDevice(port, device).

Yes, I found that, but it isn't quite clear how many ports there are to be from the one of the Core to Frontend callbacks. Also `device` goes to an enum `RETRO_DEVICE`, but that id to be used with the `device` parameter is to come from the info within the `retro_controller_description` class which is contained within that private variable `_controllerInfo` within the internal sealed class `InputHandler`.
For example, attaching the debugging and stepping through what pcsx-reamed sends is below with 7 `num_types`. If I were to make an interface with a dropdown and items to the const char* (string) within that class to callback `SetControllerPortDevice`. It would pass that `uint` to be as that `enum RETRO_DEVICE`, but all those uint values it gives appear to be way out side of those enum values except for the `standard` controller which is just `1` (I'm also assuming the `null` (0x0) it gives to just be a "None" controller).

“standard” – 1
“analog” – 261
“dualshock” – 517
“negcon” – 773
“guncon” – 260
“mouse” – 258
“” – 0 (NULL, NULL)

For a frontend to know what are the possible types of controllers it would need some way to access these descriptor strings and their corresponding id with it. I may need to look into modifying the code myself for how to expose this info.... but it isn't quite clear what the max number of `port` is to be to from this information. 

> I had a working UI with names like Lightgun/DualShock/etc... but it looks like the refactoring wasn't finished... You should be able to access the id to name mapping by making the _controllerDescriptions/_controllersInfo variables public and public properties on the bridge to access them. They should not be empty if the core calls the SetControllerInfo callback.

I wasn't referring to `_controllerDescriptions`/`_controllersInfo` being empty. Those actually have valid data in them once that bug is fixed. It's just that `ControllersMap` from the Instances is empty and appears to be unfinished I'm assuming as it appears to be unused. `ControllersMap` is linked below
https://github.com/Skurdt/SK.Libretro/blob/cf14f8392a40119542a9e0d66a89d096ec4aa4db/Unity/Scripts/Runtime/LibretroInstance.cs#L47

> I'm not sure what you mean by stack variable being updated. This is a local variable but it's both a class and is created using Marshal.PtrToStructure so it's obviously not on the stack. And even then, when the loop comes around it creates a new variable altogether. I never had any issues creating a new instance of a class and add it to a list, but maybe there's something else going on?

I may be wrong there... I'm a C/C++ engineer by trade (not really a C# guru here), but a local variable is just something I'd assume to be on a stack. I don't see it creating a new variable altogether but rather reusing the same variable... Anyways... something is already off

> Remapping buttons is done on the frontend side, if using the input system, then add/replace the mappings there in Unity. The LibretroUnityFE repo has some starting point on how to do that but that's not fully implemented (it also has the descriptors for input but not in the latest commit...)

I see... so just `_inputDescriptors` is used for informational purposes only?

**Comment by Skurdt** [comment]
It's impossible to know the number of ports, everything is callback based. A core asks every frame the state of all buttons for all ports it wants, this library only act as a bridge to gather everything to send it all back.
Basically, you can join 20 players on the unity side and it will store all the states for all 20 players for 1 frame.
If the core only asks for 2 players (like port 0 and 1 or whatever integer it uses... some core a very weird), then only those 2 sets of data are used by it (for the pcsx_rearmed core, it processes 8 players. Or at least it defines 8 controllers, maybe per game the request varies... No idea to be honest).

The “” – 0 (NULL, NULL) is because they don't send the array length along with it. It's basically how they send a variable length array in C, the receiver advances on the pointer until there's a null entry.

Those uints are not necessarily wrong, the values in the base enum are base input devices, libretro uses a subclass system where one value can shift to whatever the core wants to do.

libretro.h defines these:
```c
#define RETRO_DEVICE_TYPE_SHIFT         8
#define RETRO_DEVICE_MASK               ((1 << RETRO_DEVICE_TYPE_SHIFT) - 1)
#define RETRO_DEVICE_SUBCLASS(base, id) (((id + 1) << RETRO_DEVICE_TYPE_SHIFT) | base)
```

pcsx_rearmed defines these:
```c
#define RETRO_DEVICE_PSE_STANDARD   RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD,   0)
#define RETRO_DEVICE_PSE_ANALOG     RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_ANALOG,   0)
#define RETRO_DEVICE_PSE_DUALSHOCK  RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_ANALOG,   1)
#define RETRO_DEVICE_PSE_NEGCON     RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_ANALOG,   2)
#define RETRO_DEVICE_PSE_GUNCON     RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_LIGHTGUN, 0)
#define RETRO_DEVICE_PSE_MOUSE      RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_MOUSE,    0)
```

In any case, the last null value should be ignored and you probably shouldn't send that as the device.

I pushed a commit that uses the device map, though I haven't tried accessing it yet in the UI. Do with that what you can...

**Comment by XenuIsWatching** [comment]
> It's impossible to know the number of ports, everything is callback based. A core asks every frame the state of all buttons for all ports it wants, this library only act as a bridge to gather everything to send it all back.

I think I just figured this out, by just reading the documentation of retro arch (aka the source code). This can be just a simple counter within that same function as here
https://github.com/libretro/RetroArch/blob/903f540c057d3c29321fa678c81e26be56f65f3c/runloop.c#L2823C14-L2823C14

> Basically, you can join 20 players on the unity side and it will store all the states for all 20 players for 1 frame. If the core only asks for 2 players (like port 0 and 1 or whatever integer it uses... some core a very weird), then only those 2 sets of data are used by it (for the pcsx_rearmed core, it processes 8 players. Or at least it defines 8 controllers, maybe per game the request varies... No idea to be honest). Similarly, if you only join 1 player and the cores asks for more, the wrapper will send all 0 for all other ports.
> 
> The “” – 0 (NULL, NULL) is because they don't send the array length along with it. It's basically how they send a variable length array in C, the receiver advances on the pointer until there's a null entry.

Yeah, that make sense

> Those uints are not necessarily wrong, the values in the base enum are base input devices, libretro uses a subclass system where one value can shift to whatever the core wants to do.
> 
> libretro.h defines these:
> 
> ```c
> #define RETRO_DEVICE_TYPE_SHIFT         8
> #define RETRO_DEVICE_MASK               ((1 << RETRO_DEVICE_TYPE_SHIFT) - 1)
> #define RETRO_DEVICE_SUBCLASS(base, id) (((id + 1) << RETRO_DEVICE_TYPE_SHIFT) | base)
> ```
> 
> pcsx_rearmed defines these:
> 
> ```c
> #define RETRO_DEVICE_PSE_STANDARD   RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_JOYPAD,   0)
> #define RETRO_DEVICE_PSE_ANALOG     RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_ANALOG,   0)
> #define RETRO_DEVICE_PSE_DUALSHOCK  RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_ANALOG,   1)
> #define RETRO_DEVICE_PSE_NEGCON     RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_ANALOG,   2)
> #define RETRO_DEVICE_PSE_GUNCON     RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_LIGHTGUN, 0)
> #define RETRO_DEVICE_PSE_MOUSE      RETRO_DEVICE_SUBCLASS(RETRO_DEVICE_MOUSE,    0)
> ```
> 
> In any case, the last null value should be ignored and you probably shouldn't send that as the device.

I see... So I was misunderstanding in how it works. Then it appears in the "NONE" case, it would just be an id of `0`.

> I pushed a commit that uses the device map, though I haven't tried accessing it yet in the UI. Do with that what you can...

Thanks!! I took a quick look. I'll have to try it out. There is also the `_buttonDescriptors` that would need to be exposed... but I don't think that's quick as high of priority for what I'm about to get into.
Also, sorry I'm doing PRs here, it's rather complicated how much I've forked the repo since then with getting Android support (Quest 2) on Unity (but given the news which I'm sure you've seen that came out, who knows if it's more interesting getting this library working on something like maybe Godot) (I'll get around to publishing what I've already done soon here).... but another issue I found was with the analog to digital code here.
https://github.com/Skurdt/SK.Libretro/blob/e55306956a3b13a3533d74ad795c1e5328b9b6d4/Unity/Scripts/Runtime/Input/PlayerInputProcessor.cs#L176

Essentially, what was going on was that with an analog stick, a user could hold the stick in the upper left corner and then roll around to the bottom right never returning to the 0,0 position which will enter the cancel function clearing every bit. What would happen is those bits would be stuck on for 'up' and 'left' because the `SetBitIf` function can only set bits, it will never clear them. I also found that the left and right were swapped. This was just a simple change to the below (it may be an interesting single enhancement to make that analog2digital flag an enum to select between NONE, LEFT_ANALOG, or RIGHT_ANALOG  rather than only having the option for the left)
```cs
_joypadButtons.SetBit((uint)RETRO_DEVICE_ID_JOYPAD.UP, AnalogLeftY > 0);
_joypadButtons.SetBit((uint)RETRO_DEVICE_ID_JOYPAD.DOWN, AnalogLeftY < 0);
_joypadButtons.SetBit((uint)RETRO_DEVICE_ID_JOYPAD.LEFT, AnalogLeftX < 0);
_joypadButtons.SetBit((uint)RETRO_DEVICE_ID_JOYPAD.RIGHT, AnalogLeftX > 0);
```

> > I see... so just _inputDescriptors is used for informational purposes only?
> 
> Most of the stuff stored on the library side that comes from the core are to interpret and use on the fe side (UI, all sorts of different IDs, etc...). You can either send it back (like for input data), show as visual elements to a user or simply ignore.

Yeah.... that's what it appears like to me.

**Comment by Skurdt** [comment]
> I see... So I was misunderstanding in how it works. Then it appears in the "NONE" case, it would just be an id of 0.

Like I said, I don't think you should set it to none, it's only used to tell the end of the array. In the commit I pushed, I skipped it and it's not added to the collection. The issue is that a core may or may not handle a 0... I prefer not tempting luck in this project, it rarely worked to do so so far :p
Most gaming systems don't care how many controllers are physically plugged in, adding a new player is basically done by pressing a menu that selects multiplayer, press a button on a different device or add a coin in a different coin slot (arcade).

I also said that you can ignore data and not store it/send it back but in a lot of cases, I have to... All of the attempts to implement this all thing, publicly available when I started this, either ignored or didn't implement a lot of the environment callbacks. It made a lot of cores stall or straight up crash (mostly crashes :p).

I don't know about the AnalogToDigital stuff, it was mostly untested, quite niche and the name is kinda wrong... It's here because mame2003_plus (maybe others), when set to digital input (in the core options) was doing some weird mappings and didn't allow the sticks to be processed as buttons for whatever reason.
For the right stick, it didn't make sense to implement the workaround, digital input never(?) include a right stick (aka. a right side DPad).

The input system for unity did change also, and the entire performed/cancelled/started thing didn't behave the same for me depending on the versions... In more recent projects, I use the interface based way instead of registering to these events manually.

I don't really care about the Unity news, I don't make any money with it.
But if I were to switch engine, I wouldn't go godot but rather unreal, adding libretro support in C++ should be less buggy as well (hope...).

**Comment by XenuIsWatching** [comment]
Thanks for the commit you pushed up! That did allow me to read the descriptors and id for my UI.

https://youtu.be/nDFg0RJCp3w?si=J4tIBiCkfkAUNSx2&t=195
